sudo: required
dist: trusty
language: node_js
node_js:
- 8
script: npm run test && npm run test-coverage && npm run build
deploy:
  provider: npm
  on:
    tags: true
  skip_cleanup: true
  email: michal.perlakowski+npm@gmail.com
  api_key:
    secure: MiCo9tT/X/3hBAw44PwUCN7LWNh3+XQ/Xh6YbdsybLRpuFcypaU8CotzrisaEuKTp/Um4Jyyufq+kBgju1mRmVmYI40CCzMzlbShJQLtB/3qIkplUgQUN/9QeOHArvmdhLN0hKotdjJMcTlNxJBbqIZEGFVlPDXLZ9JSF+gOz1nFAqShz0wngE1so9Av3xcdJtLIcYsE1cSxbGfA2Mon2cTy9SBYCpnzyH0+NoYTm7EG7EFMigJE6c4bLfwHmCDjePgR4ovbQtEx+DT61ZZU/CzBt1yI/8WPz0ltVjbvgi+zkbz4UCrD3uxcaJ2s9N0NVOY6X62OERvQw2RdkXohaM0lxSJ9muFIWI8kriPzPlqo62b+w7Ro/r3UELZvzvTaCX7vcXkBGgu+ceeBjT+Qhk8B1Eg4PHKfWTZOU6rMYehDqHXZvfmQYtQD47mF3jMWxyOI7QnJ/vYnKncXVwsCVsWKVXFOSQd3rtfrMKrtXt5Pc48BdGf7r0uElT24sdR+uoM0YmnvfI7p3Bu/OVmqsi3JYLQzYUjogAbcPw+7IVdgpK8PQYFnYdMJ9fI2AaJZcHgCH9HHDB8Ev8nDAfIm8zpGXyfn+4Rqm66938g7Wc2WEaZOdnFpLciX7XLAAyX9c0VFM8G5ETXkh6lWJPtoj6TspP3Dwec9u2+sn12sWp4=
