sudo: required
dist: trusty
language: node_js
node_js:
- 10
script: npm run test-coverage && npm run build
deploy:
  provider: npm
  on:
    tags: true
  skip_cleanup: true
  email: michal.perlakowski+npm@gmail.com
  api_key:
    secure: k9iFHCoKaxObtsW5wn+SgjCS4mGvJOp/a6ZUVmoohsVZUMaQio9ROPKRoT4ORB2ZQdeVUtV8Q9w1+d9OCzvGLsINWjtsc8B2XCFE1TU1C1vhPevnsO2H2wFV5jnbBkYj8pJE4gsEUU5XQBAvxlPd2+6z3kWBkWt6viV8kRHdgq6pKMMu0qvVjk1qjWa14IgkYJyscuiZ0r3gRhF5Z3rX/FeGT3mXntLEJ/OwIFCbQDCj/OKrjKov54Qxfkngpc1kjn/WGDzcvd2dmYQDx+ySNs9BNot+F7SRDvNLOpPBuvbOo1t+0OLzTYNd/QGNTWXvHLgCflm0YWB1W+ahgivFaPgFZcPREY1H1jJeHJxCh92BLjwZB+ugoCoa0vVs0WdVG/1cQaUP2jkW4Y58E3Qdx3SgrVUXDzXqi//EbT0w+kGipp6PQSOci6QUragm4bdsp9akPVUFKvbf+Zkbg9BsABIxqW+TVa9W2nx7qiJHYTHQXdaYfTr4NknIYcc2el3uQhQexU/rNbT47VbPKYon8gmrLcRXH27isCDWq5orcLYdqrcnvBN/sLeEh3kNYZNmqI0SjBBw/NKY67w+fwNlaBBY6vmXyyRsgz5ksWqoS9NQaw4BJtOOSdd/jrBWD2PEA0ZG/Lfb1Us+SWJ8300LypYRMoYJGIScimXTkcAoL8M=
